### ISSUE TITLE
Sugerencia.

### ISSUE THREAD

**Issue by ghost** [pdepviernestm/presentacion-2022-Milagros-Trejo#1]
Hola Milagros, que bueno ver hinchas de Fnatic, recuerdo simpatizar con ellos allá por el 2015. Muy buena presentación y muy buen autorretrato! Estaría bueno que subas una foto tuya también para poder comparar.

**Comment by Milagros-Trejo** [comment]
Buen Fnatic el de 2015 jajaj. Ahí lo corregí, gracias!
